//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HungerGamesProjectV2.Components.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loc_Player
    {
        public int id { get; set; }
        public Nullable<int> location_id { get; set; }
        public Nullable<int> player_id { get; set; }
        public Nullable<int> event_id { get; set; }
    
        public virtual Hunger_Events Hunger_Events { get; set; }
        public virtual Locations Locations { get; set; }
        public virtual Players Players { get; set; }
    }
}
