//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HungerGamesProjectV2.Components.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Players()
        {
            this.Loc_Player = new HashSet<Loc_Player>();
            this.Player_Items_Inventory = new HashSet<Player_Items_Inventory>();
        }
    
        public int player_id { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_event { get; set; }
        public Nullable<decimal> player_weight { get; set; }
        public Nullable<decimal> player_height { get; set; }
        public string player_state { get; set; }
    
        public virtual Hunger_Events Hunger_Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loc_Player> Loc_Player { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player_Items_Inventory> Player_Items_Inventory { get; set; }
        public virtual Users Users { get; set; }
    }
}
