//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HungerGamesProjectV2.Components.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player_Items_Inventory
    {
        public int player_items_inventory_id { get; set; }
        public Nullable<int> player_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<int> item_qnt { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Items Items1 { get; set; }
        public virtual Players Players { get; set; }
    }
}
