//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HungerGamesProjectV2.Components.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viewers
    {
        public int viewer_id { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_event { get; set; }
    
        public virtual Hunger_Events Hunger_Events { get; set; }
        public virtual Users Users { get; set; }
    }
}
