//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HungerGamesProjectV2.Components.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote_Users
    {
        public int vote_users_id { get; set; }
        public Nullable<int> player { get; set; }
        public Nullable<int> player_votes_qnt { get; set; }
    }
}
